# -*- coding: utf-8 -*-
# Deployment settings for Another_Towers.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['/Developer/Marmalade/6.3/s3e/makefile_builder/mkb.py', '/Users/jnick/Projects/Another_Towers/template/marmalade/Another_Towers.mkb', '--deploy-only']
mkb = '/Users/jnick/Projects/Another_Towers/template/marmalade/Another_Towers.mkb'
mkf = ['/Developer/Marmalade/6.3/modules/IwGL/IwGL.mkf', '/Developer/Marmalade/6.3/modules/iwutil/iwutil.mkf', '/Developer/Marmalade/6.3/modules/third_party/libjpeg/libjpeg.mkf', '/Developer/Marmalade/6.3/modules/third_party/libpng/libpng.mkf', '/Developer/Marmalade/6.3/modules/third_party/zlib/zlib.mkf', '/Developer/Marmalade/6.3/modules/iwhttp/iwhttp.mkf', '/Developer/Marmalade/6.3/extensions/s3eDialog/s3eDialog.mkf', '/Users/jnick/Projects/Another_Towers/cocos2dx/proj.marmalade/cocos2dx.mkf', '/Users/jnick/Projects/Another_Towers/cocos2dx/platform/third_party/marmalade/libxml2.mkf', '/Users/jnick/Projects/Another_Towers/cocos2dx/platform/third_party/marmalade/freetype.mkf', '/Users/jnick/Projects/Another_Towers/cocos2dx/platform/third_party/marmalade/libtiff/libtiff.mkf', '/Users/jnick/Projects/Another_Towers/extensions/proj.marmalade/cocos2dx-ext.mkf', '/Users/jnick/Projects/Another_Towers/CocosDenshion/proj.marmalade/CocosDenshion.mkf', '/Users/jnick/Projects/Another_Towers/pugixml/pugixml.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('/Users/jnick/Projects/Another_Towers/template/marmalade/Data/Fonts', 'Fonts', 0),
    ('/Users/jnick/Projects/Another_Towers/template/marmalade/Data/Textures/512_384', 'Textures/512_384', 0),
    ('/Users/jnick/Projects/Another_Towers/template/marmalade/Data/Textures/960_640', 'Textures/960_640', 0),
    ('/Users/jnick/Projects/Another_Towers/template/marmalade/Data/Textures/1024_768', 'Textures/1024_768', 0),
    ('/Users/jnick/Projects/Another_Towers/template/marmalade/Data/Textures/2048_1536', 'Textures/2048_1536', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Another_Towers'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Another_Towers'
    long_caption = 'Another_Towers'
    version = [0, 0, 1]
    config = ['/Users/jnick/Projects/Another_Towers/template/marmalade/Data/app.icf']
    data_dir = '/Users/jnick/Projects/Another_Towers/template/marmalade/Data'
    iphone_link_lib = ['s3eDialog']
    linux_ext_lib = []
    android_extra_application_manifest = []
    iphone_link_libdir = ['/Developer/Marmalade/6.3/extensions/s3eDialog/lib/iphone']
    iphone_link_libdirs = []
    iphone_link_opts = []
    android_external_jars = ['/Developer/Marmalade/6.3/extensions/s3eDialog/lib/android/s3eDialog.jar']
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    win32_ext_dll = ['/Developer/Marmalade/6.3/extensions/s3eDialog/lib/win32/s3eDialog.dll']
    android_so = ['/Developer/Marmalade/6.3/extensions/s3eDialog/lib/android/libs3eDialog.so']
    osx_ext_dll = ['/Developer/Marmalade/6.3/extensions/s3eDialog/lib/osx/libs3eDialog.dylib']
    iphone_link_libs = []
    target = {
         'x86' : {
                   'debug'   : r'/Users/jnick/Projects/Another_Towers/template/marmalade/build_another_towers_xcode/build/Debug/Another_Towers.s86',
                   'release' : r'/Users/jnick/Projects/Another_Towers/template/marmalade/build_another_towers_xcode/build/Release/Another_Towers.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'/Users/jnick/Projects/Another_Towers/template/marmalade/build_another_towers_xcode/build/Debug ARM/Another_Towers.s3e',
                   'release' : r'/Users/jnick/Projects/Another_Towers/template/marmalade/build_another_towers_xcode/build/Release ARM/Another_Towers.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
